# Generated by Django 5.0.7 on 2024-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_id", models.IntegerField()),
                ("venta_fecha", models.DateField()),
                ("venta_monto", models.IntegerField()),
                ("venta_cantidad", models.IntegerField()),
            ],
        ),
    ]
